services:

  # ==========================================================
  # PostgreSQL
  # ==========================================================

  postgres-db-paises:
    image: postgres:16
    container_name: postgres-db-paises
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data_paises:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - postgres_network_paises

  # ==========================================================
  # pgAdmin
  # ==========================================================

  pgadmin-web-paises:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-web-paises
    depends_on:
      postgres-db-paises:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data_paises:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - postgres_network_paises

volumes:
  postgres_data_paises:
  pgadmin_data_paises:

networks:
  postgres_network_paises:
    driver: bridge
